basePath: /api/v1
definitions:
  dtos.ChoreResponseModel:
    properties:
      assignedTo:
        type: string
      completedAt:
        type: string
      completedBy:
        type: string
      createdOn:
        type: string
      description:
        type: string
      dueDate:
        type: string
      houseId:
        type: string
      houseOwnerId:
        type: string
      id:
        type: string
      isCompleted:
        type: boolean
      isRecurring:
        type: boolean
      level:
        $ref: '#/definitions/entities.ChoreLevel'
      recurringInterval:
        type: integer
      status:
        $ref: '#/definitions/entities.ChoreStatus'
      title:
        type: string
    type: object
  dtos.CreateChoreModel:
    properties:
      assignedTo:
        type: string
      description:
        maxLength: 1000
        minLength: 5
        type: string
      dueDate:
        type: string
      houseId:
        type: string
      isRecurring:
        type: boolean
      level:
        allOf:
        - $ref: '#/definitions/entities.ChoreLevel'
        enum:
        - 10
      recurringInterval:
        maximum: 365
        minimum: 1
        type: integer
      title:
        maxLength: 200
        minLength: 3
        type: string
    required:
    - assignedTo
    - description
    - dueDate
    - houseId
    - level
    - title
    type: object
  dtos.CreateHouseModel:
    properties:
      maxMemberCount:
        maximum: 8
        minimum: 1
        type: integer
      name:
        maxLength: 100
        minLength: 3
        type: string
      ownerId:
        type: string
      type:
        enum:
        - 1
        - 2
        - 3
        example: 1
        type: integer
    required:
    - maxMemberCount
    - name
    - ownerId
    - type
    type: object
  dtos.HouseResponseModel:
    properties:
      createdOn:
        type: string
      id:
        type: string
      inviteCode:
        type: string
      maxMemberCount:
        type: integer
      memberIds:
        items:
          type: string
        type: array
      name:
        type: string
      ownerId:
        type: string
      profileImage:
        type: string
      type:
        enum:
        - 1
        - 2
        - 3
        type: integer
      updatedOn:
        type: string
    type: object
  dtos.JoinHouseByCodeModel:
    properties:
      inviteCode:
        type: string
      userId:
        type: string
    required:
    - inviteCode
    - userId
    type: object
  dtos.LoginRequestModel:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dtos.NewUserModel:
    properties:
      age:
        maximum: 150
        minimum: 0
        type: integer
      email:
        type: string
      firstName:
        maxLength: 50
        minLength: 2
        type: string
      lastName:
        maxLength: 50
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
      phoneNumber:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  dtos.SignUpUserModel:
    properties:
      email:
        type: string
      firstName:
        maxLength: 50
        minLength: 2
        type: string
      lastName:
        maxLength: 50
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  dtos.UpdateChoreStatusModel:
    properties:
      choreId:
        type: string
      status:
        allOf:
        - $ref: '#/definitions/entities.ChoreStatus'
        enum:
        - 0
    required:
    - choreId
    - status
    type: object
  dtos.UpdateUserModel:
    properties:
      age:
        maximum: 150
        minimum: 0
        type: integer
      firstName:
        type: string
      imageUrl:
        type: string
      isVerifyEmail:
        type: boolean
      isVerifyPhone:
        type: boolean
      lastName:
        type: string
      phoneNumber:
        maxLength: 15
        minLength: 10
        type: string
    type: object
  entities.ChoreLevel:
    enum:
    - 10
    - 20
    - 30
    type: integer
    x-enum-varnames:
    - Easy
    - Medium
    - Hard
  entities.ChoreStatus:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - Draft
    - Progress
    - InTest
    - Completed
  entities.User:
    properties:
      age:
        type: integer
      createdOn:
        type: string
      email:
        type: string
      firstName:
        type: string
      houseIds:
        items:
          type: string
        type: array
      id:
        type: string
      imageUrl:
        type: string
      isActive:
        type: boolean
      isVerifyEmail:
        type: boolean
      isVerifyPhone:
        type: boolean
      lastLogin:
        type: string
      lastName:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      updatedOn:
        type: string
    type: object
host: localhost:3162
info:
  contact:
    email: support@houseflow.com
    name: API Support
  description: HouseFlow API Documentation
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: HouseFlow API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login with email and password to receive JWT token
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequestModel'
      produces:
      - application/json
      responses:
        "200":
          description: Returns JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - Auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Signup with email, password, firstname, and lastname to receive
        JWT token
      parameters:
      - description: Signup request
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/dtos.SignUpUserModel'
      produces:
      - application/json
      responses:
        "201":
          description: Returns JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid credentials
          schema:
            additionalProperties: true
            type: object
      summary: User Signup
      tags:
      - Auth
  /base/health:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      tags:
      - Base
  /chore:
    post:
      consumes:
      - application/json
      description: Create a new chore in a house
      parameters:
      - description: Chore object
        in: body
        name: chore
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateChoreModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.ChoreResponseModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new chore
      tags:
      - Chore
  /chore/{id}:
    put:
      consumes:
      - application/json
      description: Update an existing chore
      parameters:
      - description: Chore ID
        in: path
        name: id
        required: true
        type: string
      - description: Chore object
        in: body
        name: chore
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateChoreModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ChoreResponseModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not found
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update chore
      tags:
      - Chore
  /chore/status:
    put:
      consumes:
      - application/json
      description: Update the status of multiple chores
      parameters:
      - description: Array of status updates
        in: body
        name: statusUpdates
        required: true
        schema:
          items:
            $ref: '#/definitions/dtos.UpdateChoreStatusModel'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update chore status
      tags:
      - Chore
  /house/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: House object
        in: body
        name: house
        required: true
        schema:
          $ref: '#/definitions/dtos.CreateHouseModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.HouseResponseModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new house
      tags:
      - House
  /house/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: Join request
        in: body
        name: joinRequest
        required: true
        schema:
          $ref: '#/definitions/dtos.JoinHouseByCodeModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.HouseResponseModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Join house by invite code
      tags:
      - House
  /user:
    post:
      consumes:
      - application/json
      description: Create a new user in the system
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.NewUserModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dtos.NewUserModel'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create new user
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a user by their ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete a user
      tags:
      - User
  /user/getByEmail:
    get:
      consumes:
      - application/json
      description: Retrieve a user by their email address
      parameters:
      - description: User email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get user by email
      tags:
      - User
  /user/getUsersByHouse:
    get:
      consumes:
      - application/json
      description: Get all members of a house with their full details
      parameters:
      - description: House ID
        in: query
        name: houseId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.User'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get users by house
      tags:
      - User
  /user/profile/{id}:
    put:
      consumes:
      - application/json
      description: Update user profile fields. Only provided (non-null) fields will
        be updated.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Fields to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.UpdateUserModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update user profile
      tags:
      - User
  /user/usersList:
    get:
      consumes:
      - application/json
      description: Get a list of all users in the system
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.NewUserModel'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: List all users
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
