name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create config.json from template
        run: cp internal/config/config.template.json internal/config/config.json

      - name: Set up flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set secrets on Fly.io
        run: flyctl secrets set MONGO_URI="${{ secrets.MONGO_URI }}" JWT_SECRET="${{ secrets.JWT_SECRET }}" --app houseflowapi
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
